language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest
notifications:
  email:
    recipients:
      - mitchelljeitani@hotmail.com
    on_success: never
    on_failure: always
